### ISSUE TITLE
Server does not check for IP address

### ISSUE THREAD

**Issue by FarukGamer** [Silhouhat/Warden#2]
for some reason, the server can not check the IP address.
This is the error message that I got from the debug mode.

> [WARDEN] ERROR: Failed to connect to IPHub API to check the IP address of Shadowsun!

**Comment by Silhouhat** [comment]
Set your API key.

**Comment by FarukGamer** [comment]
The was API key already set.

**Comment by Silhouhat** [comment]
New update should fix soon.
